server:
  port: 8080
spring:
  application:
    name: parsley-char
  profiles:
    active: local
  datasource:
    username: ${parsley.datasource.username}
    password: ${parsley.datasource.password}
    url: jdbc:postgresql://${parsley.datasource.ipAddr}:${parsley.datasource.port}/parsley_chat?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&
  # JPA/Hibernate
  jpa:
    hibernate:
      ddl-auto: validate  # Validate schema without modifying it
    show-sql: true        # Log SQL queries
    properties:
      hibernate:
        format_sql: true  # Format SQL logs for readability
        dialect: org.hibernate.dialect.PostgreSQLDialect
# mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    default-executor-type: simple
